# -*- coding: utf-8 -*-
"""hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLk-ItiolaSv4TPii4gXwpI8FpyqrBRe
"""
################################################################################
#
# FILE:
# 	hw01_oxo210006.py
# AUTHOR:
# 	Olalekan Lawrence
#	oxo210006
# DESCRIPTION:
# 	Homework 1
# 	Python program cleans dataset, analyze data , tokenize data and perform functions 
# 	such as list, sort, count, and check most frequent words in the dataset
# DEPENDENCIES:
# 	Created with google collab
# 	dependencies, and/or Libraries used, re, and counter.
#
################################################################################ 


#Task 1 - Read dataset
with open("/content/ti.txt") as dataset:
  content =dataset.read()
#Task 2 - Display the dataset
print (content)

not#Task 3 - Tokenize the words
import re
content = re.sub(r"([.,!?()])", r" \1 ", content)
word_tokens = re.findall(r'\b\w+\b', content)
print(word_tokens)
print (len(word_tokens))

#Task 4 - Count words, and ensure the,The and THE are single instances
from collections import Counter
word_count = Counter(word.lower()for word in word_tokens)
#Print wordcount
print(word_count)

#Task 5 - Sort by frequency of word tokens
sorted_word_count = dict(sorted(word_count.items(), key=lambda item: item[1], reverse=True))

#Task 6 - Display top 10 entries
top_ten_word_count= [(word, count)for word, count in sorted_word_count.items()if word.isalpha()][:10]
print(f"{'Word':<15}{'Count':<10}{'Frequency'}")
print("-" * 35)
for word, count in top_ten_word_count:
 frequency = count / len(word_tokens)
 print(f"{word.lower():<15}{count:<10}{frequency:.5f}")

#Task 7 - Calculate the word count and frequency percentage of each word
print(f"{'Word':<15}{'Count':<10}{'Frequency'}")
print("-" * 35)
for i, (word, count) in enumerate(sorted_word_count.items()):
    if word.isalpha() and i < 20:
        frequency = count / len(word_tokens)
        print(f"{word.lower():<15}{count:<10}{frequency:.5f}")